name: repo-checks

on:
  pull_request:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v2.1.2
      with:
        node-version: '12.x'
    - run: yarn install
    - run: yarn lint
    - run: yarn test